### ISSUE TITLE
Trackpad - Keyboard not working with Surface Laptop 3 

### ISSUE THREAD

**Issue by callmeteddy17** [jlempen/Surface-Laptop-3-OpenCore#2]
I'm having trouble accessing macOS because the keyboard and trackpad are not working, but the touchscreen is still usable. Note: I'm using the latest version of Windows 24h2. I noticed you mentioned needing to revert to an older version to be able to use it. Do you have any other solutions, or is there a way to reinstall that older version?

**Comment by williamoak1988** [comment]
How do you fix it? I have the same problem

**Comment by jlempen** [comment]
@williamoak1988, you need to downgrade the firmware by following my howto https://github.com/jlempen/Surface-Laptop-3-OpenCore?tab=readme-ov-file#downgrading-the-uefi-firmware in order to have a working trackpad and keyboard.
